spring:
  application:
    name: usermanagement-mock-api
  cloud:
    config:
      enabled: false

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

# Logging
logging:
  level:
    com.project.management: DEBUG
    org.springframework.web: INFO

