spring:
  application:
    name: managerproject
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/managerproject
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
